# Generated by Django 4.2.1 on 2023-05-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='username')),
                ('password', models.TextField(max_length=128, verbose_name='password')),
                ('registration_date', models.DateTimeField(verbose_name='registration_date')),
            ],
        ),
    ]
